# Generated by Django 3.1.5 on 2021-01-10 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='next_id',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=5),
        ),
    ]
