# Generated by Django 3.1.5 on 2021-01-10 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_question_next_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='next_id',
            field=models.IntegerField(default=0),
        ),
    ]
